# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Topics
    url: tags/
    weight: 20
  - name: Uses
    url: uses/
    weight: 30
  - name: Resources
    url: resources/
    weight: 40
 - name: Courses
    identifier: courses
    weight: 50
  - name: BIOL3062
    parent: courses
    url: courses/biol3062/
    weight: 10
  - name: BIOL3630
    parent: courses
    url: courses/biol3630/
    weight: 20