# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Resources
    url: resources/
    weight: 20
  - name: Topics
    url: tags/
    weight: 30
 # - name: Courses
#    url: courses/
#    weight: 50
#  - name: Uses
#   url: uses/
#    weight: 60
