---
title: Site Title
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
locale: en_US
logo: 
theme: minima
owner:
  name: Andy Horn
  avatar: bio-photo.jpg
  bio: I fiddle with such things as this too much, practice trombone and piano too
    little.
  email: aghorn@dal.ca
  twitter: binohead
  linkedin: 
  github: binohead
  orcid: 
  researchgate: 
  mendeley: 
  google:
    plus: 
    analytics: 
    verify: 
    scholar: 
  facebook: 
  instagram: 
  bing-verify: 
  stackoverflow: 
  xing: 
  lastfm: 
  tumblr: 
  pinterest: 
  foursquare: 
  steam: 
  dribbble: 
  youtube: 
  soundcloud: 
  weibo: 
  flickr: 
  codepen: 
  disqus-shortname: 
minimal_mistakes_skin: air
highlight-color: "#0000FF"
lowlight-color: "#0000FF"
creative-commons:
  cc-by: 
  cc-by-nc: 
permalink: "/:categories/:title/"
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
- jekyll-sitemap
- jekyll-seo-tag
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
include:
- ".htaccess"
exclude:
- lib
- config.rb
- Capfile
- config
- log
- Rakefile
- Rakefile.rb
- tmp
- less
- "*.sublime-project"
- "*.sublime-workspace"
- test
- spec
- Gruntfile.js
- package.json
- node_modules
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
